package com.company.day1;

public class ExceptionsJava {

    public static void main(String[] args) {

        try {

            System.out.println("test");
        }
        //catch (Exception e){}
        finally {

        }

        /**
         *
         * try should have used either with catch or finally or both
         * try block can't exist without
         */
    }
}
